# Generated by Django 5.2.8 on 2026-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_completed', models.IntegerField(default=150)),
                ('happy_clients', models.IntegerField(default=100)),
                ('team_members', models.IntegerField(default=10)),
                ('years_experience', models.IntegerField(default=5)),
            ],
        ),
    ]
