# Generated by Django 5.2.8 on 2026-06-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('review', models.TextField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
